"""
lammps/head_single_impact.py — head.lmp generator for single-impact statistics mode.

Each trial:
  1. Reloads thermalized.data (positions + velocities) to reset to the clean surface
  2. Re-establishes all groups (read_data clears per-atom group memberships)
  3. Optionally re-assigns thermal velocities via velocity create (randomize_velocities)
  4. Runs one impact event (optionally with radical pre-exposure / burst)
  5. Sweeps etch products; logs per-trial stats to impact_stats.txt and ncarbon.txt

Works for both the crystal-builder path (spec.initial_config_file is None) and the
carbon-etch path (spec.initial_config_file is set).

Restart: the submit script reads ntrials_done.txt → passes -var n_complete N to LAMMPS.
The loop variable runs from 1 to (n_trials - n_complete); trial = trial_iter + n_complete.
thermalized.data already exists on restart so the init_thermalization guard is skipped.
"""

from ..spec import SimSpec
from ..species import SPECIES
from ..orientations import ORIENT
from .head import (
    _potential_block,
    _deposit_line,
    _build_ion_dump_blocks,
    _radical_loop_block,
    _radical_burst_block,
    _expose_zone_def,
    _expose_zone_redef,
)


def get_thermalize_surface_lmp(spec: SimSpec) -> str:
    """Generate thermalize_surface.lmp for carbon-path single-impact mode.

    Standalone pre-run: loads initial_config.data, CG-minimizes, runs NVT,
    writes thermalized.data + impact_stats.txt header.
    Called from submit before head.lmp so no stopclust or impact machinery
    is active — safe for multi-cluster surfaces like graphullerene.
    """
    species   = SPECIES[spec.species]
    nvt_steps = spec.initial_thermalization_steps if spec.initial_thermalization else 0
    seed      = spec.seed_adjust + 459087

    return (
        f"# thermalize_surface.lmp — generated by DiamondEtchMD\n"
        f"# Standalone: loads data_file, thermalizes to T K, writes thermalized.data.\n"
        f"# No stopclust or impact fixes — safe for multi-cluster surfaces.\n"
        f"package kokkos neigh/qeq full neigh half newton on\n"
        f"units\t\treal\n"
        f"include     config.lmp\n"
        f'if "${{pot}} == COMB3" then &\n'
        f'"atom_style charge" &\n'
        f'elif "${{pot}} == REAX" &\n'
        f'"atom_style charge" &\n'
        f"else &\n"
        f'"atom_style atomic"\n'
        f"\n"
        f"boundary\tp p m\n"
        f"\n"
        f"read_data   ${{data_file}}\n"
        f"\n"
        f"region      bbox block EDGE EDGE EDGE EDGE EDGE EDGE\n"
        f"region      anchor block INF INF INF INF INF ${{anchor_z_max}} units box\n"
        f"\n"
        f"group       anchor region anchor\n"
        f"group       carbon type 1\n"
        f"group       hydrogen type 2\n"
        f"group       oxygen type 3\n"
        f"group       insert empty\n"
        f"group       mobile subtract all anchor\n"
        f"\n"
        f"mass        1 ${{M_C}}\n"
        f"mass        2 ${{M_H}}\n"
        f"mass        3 ${{M_O}}\n"
        f"mass        4 ${{{species['mass_var']}}}\n"
        f"\n"
        f"{_potential_block(species)}"
        f"\n"
        f"compute     mtemp mobile temp\n"
        f"compute_modify mtemp dynamic/dof yes\n"
        f"thermo      1000\n"
        f"thermo_style custom step time temp\n"
        f"thermo_modify temp mtemp\n"
        f"thermo_modify lost warn flush yes\n"
        f"\n"
        f"# CG minimization\n"
        f"fix         minimfreeze anchor setforce 0.0 0.0 0.0\n"
        f"min_style   cg\n"
        f"minimize    1.0e-4 1.0e-6 1000 10000\n"
        f"unfix       minimfreeze\n"
        f"\n"
        f"# NVT equilibration ({nvt_steps:,} steps)\n"
        f"velocity    mobile create ${{T}} {seed}\n"
        f"fix         therm_init mobile nvt temp ${{T}} ${{T}} 100.0\n"
        f"run         {nvt_steps}\n"
        f"unfix       therm_init\n"
        f"\n"
        f"write_data  initial_config_${{T}}K.data\n"
        f"write_data  thermalized.data nofix nocoeff\n"
        f"print '# trial surf_z_before_A ion_z_after_A ion_in_box pen_depth_A'"
        f" file impact_stats.txt\n"
    )


def get_head_lmp_single_impact(spec: SimSpec) -> str:
    """Generate head.lmp for single-impact statistics mode."""
    is_carbon    = spec.initial_config_file is not None
    species      = SPECIES[spec.species]
    is_burst     = spec.flux_ratio > 0 and spec.radical_burst
    is_rie       = spec.flux_ratio > 0 and not spec.radical_burst
    has_radicals = spec.flux_ratio > 0
    has_ar       = species["needs_zbl"]
    qeq_group    = "nonargon" if has_ar else "all"

    molecule_decl = "molecule O2 O2.molecule\n" if species["is_molecule"] else ""

    if is_burst:
        radical_loop = _radical_burst_block(spec)
    elif is_rie:
        radical_loop = _radical_loop_block(spec)
    else:
        radical_loop = ""

    if has_radicals:
        ncarbon_print = (
            f'print "${{trial}} ${{cn}} ${{ncarbon}} ${{nhydrogen}} ${{noxygen}}"'
            f" append ncarbon.txt\n"
        )
        write_data = f"write_data  impact_snaps/${{trial}}_${{cn}}.data nofix nocoeff\n"
    else:
        ncarbon_print = (
            f'print "${{trial}} ${{ncarbon}} ${{nhydrogen}} ${{noxygen}}"'
            f" append ncarbon.txt\n"
        )
        write_data = f"write_data  impact_snaps/${{trial}}_0.data nofix nocoeff\n"

    ion_dump_open, etch_event_block, channeling_block, ion_dump_close = (
        _build_ion_dump_blocks(spec, is_carbon_etch=is_carbon)
    )

    # Carbon path: thermalized.data is created by thermalize_surface.lmp (called from
    # submit before head.lmp), so head.lmp always starts with it present.
    # Crystal path: thermalization still lives in head.lmp via init_thermalization.lmp.
    if is_carbon:
        therm_guard = ""
    else:
        therm_guard = (
            f"# ── Initial thermalization (first run only, skipped on restart) ─────\n"
            f'if "${{n_complete}} == 0" then "include init_thermalization.lmp"\n'
            f'if "${{n_complete}} == 0" then "write_data thermalized.data nofix nocoeff"\n'
            f'if "${{n_complete}} == 0" then &\n'
            f'    "print \'# trial surf_z_before_A ion_z_after_A ion_in_box pen_depth_A\''
            f" file impact_stats.txt\"\n"
            f"\n"
        )

    randomize_block = ""
    if spec.randomize_velocities:
        randomize_block = (
            f"velocity    all create ${{T}} "
            f"$(v_trial*1000003+{spec.seed_adjust}*7+1) dist gaussian\n"
        )

    remove_ar_block = ""
    if has_ar and spec.remove_ar:
        remove_ar_block = (
            f"group       incident_ion type 4\n"
            f"delete_atoms group incident_ion\n"
            f"group       incident_ion delete\n"
            f"\n"
        )

    # ── nonargon group line: needed after every read_data for ZBL ions ────────
    nonargon_redef = "group       nonargon type 1 2 3\n" if has_ar else ""

    # ── Initial structure loading (crystal vs carbon path) ────────────────────
    if is_carbon:
        initial_load = (
            f"read_data   ${{data_file}}\n"
            f"\n"
            f"# Anchor: frozen slab below anchor_z_max (Å)\n"
            f"region          bbox block EDGE EDGE EDGE EDGE EDGE EDGE\n"
            + _expose_zone_def(spec)
            + f"region          anchor block INF INF INF INF INF ${{anchor_z_max}} units box\n"
            f"variable        channeling_z equal bound(anchor,zmin)-2.0\n"
        )
        anchor_group = (
            f"group       anchor region anchor\n"
            f"group       insert empty\n"
            f"group       carbon type 1\n"
            f"group       hydrogen type 2\n"
            f"group       oxygen type 3\n"
            f"group       mobile subtract all anchor\n"
            f"\n"
            f"variable    n_anchor_2x equal 2*count(anchor)\n"
        )
    else:
        cfg         = ORIENT[spec.orientation]
        lattice_cmd = cfg["lattice_cmd"]
        bottom_expr = cfg["bottom_expr"]
        initial_load = (
            f"region      dummy_region block 0 1 0 1 0 1\n"
            f"create_box  4 dummy_region\n"
            f"read_data   ${{data_file}} add merge\n"
            f"\n"
            f"variable    bottom equal {bottom_expr}\n"
            f"print       'BOTTOM ${{bottom}}'\n"
            f"print       'N_LAT_0 ${{n_lat_0}}'\n"
            f"\n"
            f"{lattice_cmd}\n"
            f"region          bbox block EDGE EDGE EDGE EDGE EDGE EDGE\n"
            + _expose_zone_def(spec)
            + f"variable        sublat equal ${{bottom}}+1/2\n"
            f"region          anchor block INF INF INF INF ${{bottom}} ${{sublat}} units lattice\n"
        )
        anchor_group = (
            f"group       anchor region anchor\n"
            f"group       insert empty\n"
            f"group       carbon type 1\n"
            f"group       hydrogen type 2\n"
            f"group       oxygen type 3\n"
            f"group       mobile subtract all anchor\n"
        )

    # ── In-loop reset block (top of every trial) ───────────────────────────────
    # The LAMMPS 2022 build uses old-style read_data where 'add' takes an integer
    # offset, not keywords like 'replace'.  Workaround: delete all atoms first,
    # then read_data with add 0 (zero ID offset = original IDs).
    # delete_atoms also removes any embedded Ar ion from the prior trial.
    loop_reset = (
        f"unfix       reax_qeq\n"
        f"delete_atoms group all\n"
        f"read_data   thermalized.data add 0\n"
        f"\n"
        f"# Re-establish all groups; read_data zeros per-atom group membership\n"
        f"group       anchor region anchor\n"
        f"group       carbon type 1\n"
        f"group       hydrogen type 2\n"
        f"group       oxygen type 3\n"
        f"{nonargon_redef}"
        f"group       insert empty\n"
        f"group       mobile subtract all anchor\n"
        f"\n"
        f"fix         reax_qeq {qeq_group} qeq/reaxff 1 0.0 6.0 1e-6 reaxff\n"
        f"\n"
        f"{randomize_block}"
        f"variable    cn equal 0\n"
        f"variable    cn_start equal 0\n"
        f"\n"
        f"# Snapshot surface z BEFORE impact using immediate $() evaluation\n"
        f"region      bbox delete\n"
        f"region      bbox block EDGE EDGE EDGE EDGE EDGE EDGE\n"
        + _expose_zone_redef(spec)
        + f"run         0 post no\n"
        f"variable    surf_z_before equal $(bound(carbon,zmax))\n"
    )

    # ── Per-trial stats log ────────────────────────────────────────────────────
    # ion_in_box: 1 if ion embedded, 0 if sputtered/reflected (swept away or left box)
    stats_log = (
        f"variable    ion_in_box equal count(insert)\n"
        f'if "${{ion_in_box}} > 0" then &\n'
        f'    "variable ion_z_after equal $(bound(insert,zmin))" &\n'
        f'else &\n'
        f'    "variable ion_z_after equal 9999.0"\n'
        f"variable    pen_depth equal ${{surf_z_before}}-${{ion_z_after}}\n"
        f'print "${{trial}} ${{surf_z_before}} ${{ion_z_after}} ${{ion_in_box}} ${{pen_depth}}"'
        f" append impact_stats.txt\n"
    )

    return (
        f"# head.lmp — generated by DiamondEtchMD (single-impact statistics mode)\n"
        f"# {'carbon-etch' if is_carbon else 'crystal'}  species={spec.species}"
        f"  {spec.energy}eV  {spec.surface_temperature}K"
        f"  n_trials={spec.n_trials}\n"
        f"package kokkos neigh/qeq full neigh half newton on\n"
        f"units\t\treal\n"
        f"include     config.lmp\n"
        f'if "${{pot}} == COMB3" then &\n'
        f'"atom_style charge" &\n'
        f'elif "${{pot}} == REAX" &\n'
        f'"atom_style charge" &\n'
        f"else &\n"
        f'"atom_style atomic"\n'
        f"\n"
        f"boundary\tp p m\n"
        f"\n"
        f"# ── Load initial structure ──────────────────────────────────────────\n"
        f"{initial_load}"
        f"\n"
        f"# ── Groups, masses, potential ───────────────────────────────────────\n"
        f"{anchor_group}"
        f"\n"
        f"mass        1 ${{M_C}}\n"
        f"mass        2 ${{M_H}}\n"
        f"mass        3 ${{M_O}}\n"
        f"mass        4 ${{{species['mass_var']}}}\n"
        f"\n"
        f"{_potential_block(species)}"
        f"\n"
        f"# ── Velocity components (set once; same each trial for same energy/angle) ──\n"
        f"variable \tvel equal sqrt(2*${{energ}}*6.02214129*1.0e+7/${{M_incident}}/6242)/1000\n"
        f"variable \tvelx equal sin(${{ion_angl}}*PI/180)*cos(${{ion_azimuth}}*PI/180)*${{vel}}\n"
        f"variable \tvely equal sin(${{ion_angl}}*PI/180)*sin(${{ion_azimuth}}*PI/180)*${{vel}}\n"
        f"variable \tvelz equal cos(${{ion_angl}}*PI/180)*${{vel}}\n"
        f"\n"
        f"# ── Computes ────────────────────────────────────────────────────────\n"
        f"compute     ake all ke\n"
        f"compute     ape all pe\n"
        f"compute     ike insert ke\n"
        f"variable    ate equal c_ake+c_ape+ecouple\n"
        f"\n"
        f"variable\tcheckevery equal 1000\n"
        f"compute\t    clusts all cluster/atom 3.0\n"
        f"compute\t    clust_min all reduce min c_clusts\n"
        f"compute\t    clust_max all reduce max c_clusts\n"
        f"variable    one_clust equal \"c_clust_min == c_clust_max\"\n"
        f"fix\t\t    stopclust all halt ${{checkevery}} v_one_clust == 0 error continue message yes\n"
        f"\n"
        f"compute     cclusts carbon cluster/atom 1.8\n"
        f"compute     cc1 carbon chunk/atom c_cclusts compress yes\n"
        f"compute     nclusts carbon reduce max c_cc1\n"
        f"\n"
        f"variable\tnfixed   equal count(anchor)\n"
        f"variable\tnmobile  equal count(mobile)\n"
        f"variable\tninject  equal count(insert)\n"
        f"\n"
        f"thermo_style    custom step time v_ninject temp c_ike dt ecouple v_ate v_one_clust c_nclusts\n"
        f"compute     \tmtemp mobile temp\n"
        f"compute_modify  mtemp dynamic/dof yes\n"
        f"thermo_modify   temp mtemp\n"
        f"thermo_modify   lost warn flush yes\n"
        f"\n"
        f"variable    event_count equal ${{n_events}}\n"
        f"\n"
        f"{molecule_decl}"
        f"{therm_guard}"
        f"# ── Trial loop ──────────────────────────────────────────────────────\n"
        f"# Initialize trial counter the same way 'c' works in regular mode:\n"
        f"# ${{}}-substitute the index var to get a literal number, then increment inside.\n"
        f"variable    trial equal ${{n_complete}}\n"
        f"variable    trial_remaining equal $(v_n_trials)-${{n_complete}}\n"
        f"variable    trial_iter loop ${{trial_remaining}}\n"
        f"\n"
        f"label\t\ttrial_start\n"
        f"\n"
        f"# Increment trial counter (same pattern as 'c' in regular head.lmp)\n"
        f"variable    trial equal ${{trial}}+1\n"
        f"variable    c equal ${{trial}}\n"
        f"\n"
        f"# Reset surface to thermalized state; re-establish all groups and QEQ fix\n"
        f"{loop_reset}"
        f"\n"
        f"{radical_loop}"
        f"{ion_dump_open}"
        f"variable    deposeed equal floor(random(1,72099+${{seed_adjust}},${{trial}}))\n"
        f"{_deposit_line(species, spec)}"
        f"\n"
        f"fix     2 mobile nve\n"
        f"fix     3 insert nve\n"
        f"\n"
        f"timestep 1e-10\n"
        f"run 1 post no\n"
        f"variable starting_nclusts equal $(c_nclusts)\n"
        f"\n"
        f"fix ats all dt/reset 1 NULL 1.00 0.01 units box\n"
        f"thermo      100\n"
        f"\n"
        f"variable    t0 equal $(time)\n"
        f"variable    time_elapsed equal time-${{t0}}\n"
        f"fix         thalt all halt 1 v_time_elapsed > ${{impact_time}} error continue message yes\n"
        f"\n"
        f"run         0 post no\n"
        f"variable    n_channelled equal 0\n"
        f"# =========================== begin inner loop ===========================\n"
        f"label\t\tcontinue_impact\n"
        f"\n"
        f"run         1000000000 pre no post no\n"
        f"run         0\n"
        f"{etch_event_block}"
        f"{channeling_block}"
        f"\n"
        f'if "$(time-v_t0) < ${{impact_time}}" then "jump SELF continue_impact"\n'
        f"unfix thalt\n"
        f"# ============================ end inner loop ============================\n"
        f"\n"
        f"unfix   depo\n"
        f"unfix   ats\n"
        f"\n"
        f"include thermalize.lmp\n"
        f"\n"
        f"unfix       2\n"
        f"unfix       3\n"
        f"\n"
        f"{stats_log}"
        f"\n"
        f"{write_data}"
        f"\n"
        f"{remove_ar_block}"
        f"group       carbon type 1\n"
        f"group       hydrogen type 2\n"
        f"group       oxygen type 3\n"
        f"variable    ncarbon equal count(carbon)\n"
        f"variable    nhydrogen equal count(hydrogen)\n"
        f"variable    noxygen equal count(oxygen)\n"
        f"\n"
        f"{ncarbon_print}"
        f"\n"
        f"{ion_dump_close}"
        f"# Update restart counter after each completed trial\n"
        f"shell       echo ${{trial}} > ntrials_done.txt\n"
        f"\n"
        f"next\t\ttrial_iter\n"
        f"jump\t\tSELF trial_start\n"
    )
