"""
lammps/head.py — generator for head.lmp, the main LAMMPS driver script.

head.lmp is the top-level script passed to lmp via -in.  It includes config.lmp,
sets up atom groups, the force field, computes, and runs the per-impact outer loop:

  for each impact:
    1. deposit incident particle
    2. adaptive-timestep NVE until impact_time reached or cluster separates
    3. thermalize substrate
    4. replenish carbon if etched below baseline (addfix loop)
    5. write ncarbon.txt, save restart snapshot

The lattice command and bottom expression embedded in head.lmp are
orientation-specific and are pulled from the ORIENT registry.

Species-specific behaviour (Ar ZBL, O2 molecule injection) is resolved at
generation time via the SPECIES registry — no LAMMPS-level conditionals.

Note: LAMMPS ${variable} syntax must be escaped as ${{variable}} in Python
f-strings.  LAMMPS $(expression) uses parentheses and needs no escaping.
"""

from ..orientations import ORIENT
from ..species import SPECIES
from ..spec import SimSpec


def _potential_block(species: dict) -> str:
    """Return the pair_style / pair_coeff / QEQ block for the given species."""
    if species["needs_zbl"]:
        # Ar: hybrid ReaxFF + ZBL for short-range nuclear repulsion
        return (
            f'if "${{pot}} == REAX" then &\n'
            f'"pair_style  hybrid reaxff NULL mincap 200 safezone 1.5 zbl 5.0 6.0" &\n'
            f'"pair_coeff * * reaxff ffield.reax C H O NULL" &\n'
            f'"pair_coeff 1 4 zbl 6.0 18.0" &\n'
            f'"pair_coeff 2 4 zbl 1.0 18.0" &\n'
            f'"pair_coeff 3 4 zbl 8.0 18.0" &\n'
            f'"pair_coeff 4 4 zbl 18.0 18.0" &\n'
            f'"group nonargon type 1 2 3" &\n'
            f'"fix reax_qeq nonargon qeq/reaxff 1 0.0 6.0 1e-6 reaxff"\n'
        )
    else:
        # O, O2, H: plain ReaxFF
        return (
            f'if "${{pot}} == REAX" then &\n'
            f'"pair_style reaxff NULL mincap 200 safezone 1.5" &\n'
            f'"pair_coeff * * ffield.reax C H O NULL" &\n'
            f'"fix reax_qeq all qeq/reaxff 1 0.0 6.0 1e-6 reaxff"\n'
        )


def _deposit_line(species: dict) -> str:
    """Return the fix deposit command for the given species."""
    if species["is_molecule"]:
        # O2: inject as molecule; type 0 means types come from molecule file
        return (
            f"fix     depo insert deposit 1 0 10000000000 ${{deposeed}} global "
            f"${{i_above}} ${{i_above}} vx 0.0 0.0 vy ${{vely}} ${{vely}} "
            f"vz -${{velz}} -${{velz}} region bbox units box mol O2\n"
        )
    else:
        # single atom: inject by type index
        return (
            f"fix     depo insert deposit 1 ${{incident_type_index}} 10000000000 ${{deposeed}} global "
            f"${{i_above}} ${{i_above}} vx 0.0 0.0 vy ${{vely}} ${{vely}} "
            f"vz -${{velz}} -${{velz}} region bbox units box\n"
        )


def get_head_lmp(spec: SimSpec) -> str:
    """Generate the contents of head.lmp for the given SimSpec."""
    cfg = ORIENT[spec.orientation]
    lattice_cmd = cfg["lattice_cmd"]
    bottom_expr = cfg["bottom_expr"]
    species = SPECIES[spec.species]

    # O2 molecule declaration (before the loop)
    molecule_decl = ""
    if species["is_molecule"]:
        molecule_decl = f"molecule O2 O2.molecule\n"

    # Ar: re-establish nonargon group at top of each loop iteration
    nonargon_regroup = ""
    if species["needs_zbl"]:
        nonargon_regroup = f"group nonargon type 1 2 3\n"

    # Post-impact removal for inert species (Ar)
    removal_block = ""
    if species["remove_after_impact"]:
        removal_block = (
            f"\n"
            f"# Remove {spec.species} (inert, does not participate in chemistry)\n"
            f"group       IonRemove type {species['type_index']}\n"
            f"delete_atoms group IonRemove\n"
            f"group       IonRemove delete\n"
        )

    return (
        f"# head.lmp — generated by DiamondEtchMD\n"
        f"# orientation={spec.orientation}  species={spec.species}"
        f"  {spec.energy}eV  {spec.temperature}K  angle={spec.angle}deg\n"
        f"package kokkos neigh/qeq full neigh half newton on\n"
        f"units\t\treal\n"
        f"include     config.lmp\n"
        f'if "${{pot}} == COMB3" then &\n'
        f'"atom_style charge" &\n'
        f'elif "${{pot}} == REAX" &\n'
        f'"atom_style charge" &\n'
        f"else &\n"
        f'"atom_style atomic"\n'
        f"\n"
        f"boundary\tp p m\n"
        f"\n"
        f"# create_box with 4 types then merge data file so type 4 (Ar) is available\n"
        f"region      dummy_region block 0 1 0 1 0 1\n"
        f"create_box  4 dummy_region\n"
        f"read_data   ${{data_file}} add merge\n"
        f"\n"
        f"variable \tlp equal $(v_end_fluence*v_ML)-${{n_complete}} # impacts left\n"
        f"variable    a loop ${{lp}}\n"
        f"variable    bottom equal {bottom_expr}\n"
        f"print       'BOTTOM ${{bottom}}'\n"
        f"print       'N_LAT_0 ${{n_lat_0}}'\n"
        f"\n"
        f"# Regions — lattice must match make_surf.lmp for this orientation\n"
        f"{lattice_cmd}\n"
        f"region          bbox block EDGE EDGE EDGE EDGE EDGE EDGE\n"
        f"variable        sublat equal ${{bottom}}+1/2\n"
        f"region          anchor block INF INF INF INF ${{bottom}} ${{sublat}} units lattice\n"
        f"\n"
        f"# Groups\n"
        f"group \tanchor region anchor\n"
        f"group\tinsert empty\n"
        f"group \tmobile subtract all anchor\n"
        f"group   carbon type 1\n"
        f"\n"
        f"# Particle masses (4 types: C, H, O, Ar)\n"
        f"mass        1 ${{M_C}}\n"
        f"mass        2 ${{M_H}}\n"
        f"mass        3 ${{M_O}}\n"
        f"mass        4 ${{M_Ar}}\n"
        f"\n"
        f"# Potential\n"
        f"{_potential_block(species)}"
        f"\n"
        f"# Pre-run counters\n"
        f"variable c equal ${{n_complete}}\n"
        f"variable event_count equal ${{n_events}}\n"
        f"\n"
        f"# Atom counts\n"
        f"variable\tnfixed   equal count(anchor)\n"
        f"variable\tnmobile  equal count(mobile)\n"
        f"variable \tninject  equal count(insert)\n"
        f"\n"
        f"# Incident particle velocity components\n"
        f"variable \tvel equal sqrt(2*${{energ}}*6.02214129*1.0e+7/${{M_incident}}/6242)/1000\n"
        f"variable \tvelz equal cos(${{angl}}*PI/180)*${{vel}}\n"
        f"variable \tvely equal sin(${{angl}}*PI/180)*${{vel}}\n"
        f"\n"
        f"# Energy conservation check\n"
        f"compute     ake all ke\n"
        f"compute     ape all pe\n"
        f"compute     ike insert ke\n"
        f"variable    ate equal c_ake+c_ape+ecouple\n"
        f"\n"
        f"# Clustering\n"
        f"variable\tcheckevery equal 1000\n"
        f"compute\t    clusts all cluster/atom 3.0\n"
        f"compute\t    clust_min all reduce min c_clusts\n"
        f"compute\t    clust_max all reduce max c_clusts\n"
        f"variable    one_clust equal \"c_clust_min == c_clust_max\"\n"
        f"fix\t\t    stopclust all halt ${{checkevery}} v_one_clust == 0 error continue message yes\n"
        f"\n"
        f"# Carbon cluster event tracking\n"
        f"compute     cclusts carbon cluster/atom 1.8\n"
        f"compute     cc1 carbon chunk/atom c_cclusts compress yes\n"
        f"compute     nclusts carbon reduce max c_cc1\n"
        f"\n"
        f"# Thermo\n"
        f"thermo_style    custom step time v_ninject temp c_ike dt ecouple v_ate v_one_clust c_nclusts\n"
        f"compute     \tmtemp mobile temp\n"
        f"compute_modify  mtemp dynamic/dof yes\n"
        f"thermo_modify   temp mtemp\n"
        f"thermo_modify   lost warn flush yes\n"
        f"\n"
        f'print "${{c}}" file begin.txt\n'
        f"{molecule_decl}"
        f"\n"
        f"# ========================= Begin Per-Impact Outer Loop =========================\n"
        f"label\t\tloop\n"
        f"\n"
        f"dump current_dump all custom 100 dumps/event_dump_${{event_count}}.dump id type x y z vx vy vz fx fy fz q\n"
        f"\n"
        f"group       insert clear\n"
        f"group \t    mobile subtract all anchor\n"
        f"{nonargon_regroup}"
        f"\n"
        f"variable    c equal ${{c}}+1\n"
        f"variable    deposeed equal floor(random(1,72099+${{seed_adjust}},${{c}}))\n"
        f"{_deposit_line(species)}"
        f"\n"
        f"fix     2 mobile nve\n"
        f"fix     3 insert nve\n"
        f"\n"
        f"# Run 1 fs timestep to place incident particle\n"
        f"timestep 1e-10\n"
        f"run 1 post no\n"
        f"variable starting_nclusts equal $(c_nclusts)\n"
        f"\n"
        f"# Adaptive timestep\n"
        f"fix ats all dt/reset 1 NULL 1.00 0.01 units box\n"
        f"thermo      100\n"
        f"\n"
        f"variable    t0 equal $(time)\n"
        f"variable    time_elapsed equal time-${{t0}}\n"
        f"fix         thalt all halt 1 v_time_elapsed > ${{impact_time}} error continue message yes\n"
        f"\n"
        f"run         0 post no\n"
        f"# =========================== begin inner loop ===========================\n"
        f"label\t\tcontinue_impact\n"
        f"\n"
        f"run         1000000000 pre no post no\n"
        f'if "$(time-v_t0) > ${{impact_time}}" then "run 0"\n'
        f'if "${{one_clust}} == 0" then "include sweep.lmp"\n'
        f'if "$(c_nclusts) > ${{starting_nclusts}}" then &\n'
        f'"variable event_count equal ${{event_count}}+1" &\n'
        f'"variable starting_nclusts equal $(c_nclusts)"\n'
        f'if "$(time-v_t0) < ${{impact_time}}" then "jump SELF continue_impact"\n'
        f"unfix thalt\n"
        f"# ============================ end inner loop ============================\n"
        f"\n"
        f"unfix   depo\n"
        f"unfix   ats\n"
        f"{removal_block}"
        f"\n"
        f"# Thermalize\n"
        f"include thermalize.lmp\n"
        f"\n"
        f"unfix       2\n"
        f"unfix       3\n"
        f"\n"
        f"# Replenish carbon if etched below baseline\n"
        f"group       carbon type 1\n"
        f"group       hydrogen type 2\n"
        f"group       oxygen type 3\n"
        f"variable    ncarbon equal count(carbon)\n"
        f"variable    nhydrogen equal count(hydrogen)\n"
        f"variable    noxygen equal count(oxygen)\n"
        f"label addfix\n"
        f'if "${{ncarbon}}<${{n_lat_0}}" then &\n'
        f'"include addfix.lmp" &\n'
        f'"fix 2 mobile nve" &\n'
        f'"include thermalize.lmp" &\n'
        f'"unfix 2"\n'
        f'if "${{ncarbon}}<${{n_lat_0}}" then "jump SELF addfix"\n'
        f"\n"
        f'print "Run ${{c}} complete"\n'
        f'print "C_COUNT: ${{ncarbon}}"\n'
        f'print "${{c}} ${{ncarbon}} ${{nhydrogen}} ${{noxygen}}" append ncarbon.txt\n'
        f"\n"
        f"write_data data_files/${{c}}.data nofix nocoeff\n"
        f"if '$(v_c%v_ML) == 0' then \"write_dump all custom dumps/dump.dump id type x y z vx vy vz modify sort id append yes\"\n"
        f"\n"
        f"undump current_dump\n"
        f"# ========================= End Per-Impact Outer Loop =========================\n"
        f"next\t\ta\n"
        f"jump\t\tSELF loop\n"
    )
