#!/bin/bash
#SBATCH --job-name=explore_110
#SBATCH --nodes=1
#SBATCH --mem=16G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --time=00:30:00
#SBATCH --account=dgraves

module purge
module load lammps/kokkos/gpu_della9_2022

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PROC_BIND=spread
export OMP_PLACES=threads

srun lmp -k on g 1 -sf kk -in make_surf_110.lmp
